### ISSUE TITLE
when i run appium doctor , i got the below error using appium 1.5.2

### ISSUE THREAD

**Issue by Sushmaemmadi** [appium-boneyard/appium-dot-app#586]
'/Applications/Appium 2.app/Contents/Resources/node/bin/node' '/Applications/Appium 2.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
module.js:341
    throw err;
    ^

Error: Cannot find module '/Applications/Appium 2.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by JamieEdge** [comment]
This project isn’t maintained anymore. Please see https://github.com/appium/appium-desktop

**Comment by Sushmaemmadi** [comment]
Thanks, I am new to Appium, how can i check whether my Appium setup properly or not?

if you could provide me any tutorial, that would be helpfull
